<div id="storefinder" class="storefinder-search-container">
    <form>
        <input id="storefinder-text-input" type="text"
               placeholder="<?php echo $this->__('Enter postcode or place name')?>" required>
        <input id="storefinder-button-find" type="button" value="Find">
    </form>
    <div class="storefinder-geolocation"><a id="storefinder-geolocation-find"><?php echo $this->__('Use my current position')?></a></div>
    <div id="storefinder-ajax-loader"><img src="/skin/frontend/default/default/images/opc-ajax-loader.gif"></div>
</div>